### ISSUE TITLE
v1.0 tasks don't run on Symfony 2.8

### ISSUE THREAD

**Issue by andyexeter** [capistrano/symfony#119]
No matter what I try I can't seem to get any tasks to run using Symfony 2.8. Using the `--trace` option I see that the tasks are invoked but they just seem to do nothing:

```
** Invoke deploy:updated (first_time)
** Invoke composer:install (first_time)
** Execute composer:install
** Invoke composer:run (first_time)
** Execute composer:run
00:09 composer:run
      01 composer install --no-interaction --quiet --optimize-autoloader
    ✔ 01 user@example.org 5.309s
** Execute deploy:updated
** Invoke symfony:cache:warmup (first_time)
** Execute symfony:cache:warmup
** Invoke symfony:clear_controllers (first_time)
** Execute symfony:clear_controllers
** Invoke deploy:publishing (first_time)
** Execute deploy:publishing
```

I am using version 1.0. I have tried setting the following in my `deploy.rb` file:

```ruby
set :symfony_directory_structure, 2
set :sensio_distribution_version, 4
```

Which doesn't help. I then also tried adding the following:

```ruby
set :symfony_console_path, "app/console"
set :config_path, "app/config"
set :web_path, "web"
set :cache_path, "app/cache"
set :log_path, "app/log"
```

I have also tried adding the :web, :app and :db roles to the server but no matter what I do the tasks don't run. The only way I can get the tasks to run is by downgrading to v0.4.0.

**Comment by Nyholm** [comment]
Does it work if you add `set :symfony_deploy_roles, :web`?
