### ISSUE TITLE
Unable to set SYMFONY_ENV on FreeBSD

### ISSUE THREAD

**Issue by nuqqsa** [capistrano/symfony#24]
```
$ bundle exec cap production deploy
INFO[6a80bc06] Running /usr/bin/env mkdir -p /tmp/app/ on host.com
DEBUG[6a80bc06] Command: ( SYMFONY_ENV=prod /usr/bin/env mkdir -p /tmp/app/ )
DEBUG[6a80bc06] 	SYMFONY_ENV=prod: Command not found.
```

In FreeBSD the command should look like this:
```
setenv SYMFONY_ENV prod
```

**Comment by bantu** [comment]
Are you sure this is a FreeBSD issue? You're probably just using a shell that doesn't support "SYMFONY_ENV=prod".

**Comment by peterjmit** [comment]
Closing as this is an issue for the main capistrano repository/SSHkit (and likely not an issue there either)

**Comment by webdevilopers** [comment]
Did you find a solution to this @nuqqsa ? Indeed I am facing the same issue on FreeBSD too.

**Comment by nuqqsa** [comment]
The workaround for us was to change the default shell to bash. In FreeBSD that is CSH.

**Comment by webdevilopers** [comment]
Did you have to set this globally on your server or via capistrano task? Maybe this could be interesting for other FreeBSD users too.

**Comment by webdevilopers** [comment]
For anybody interested here is a tutorial how to change the default bash in FreeBSD:
http://www.cyberciti.biz/faq/howto-set-bash-as-your-default-shell/

This solved my problem.
