### ISSUE TITLE
how to run a console command?

### ISSUE THREAD

**Issue by jurgenweber** [capistrano/symfony#28]
I found in your readme...
```
namespace :deploy do
  task :migrate do
    invoke 'symfony:console', 'doctrine:migrations:migrate', '--no-interaction', 'db'
  end
end
```
but
```
SSHKit::Runner::ExecuteError: Exception while executing on host vagrant-front01.local: Don't know how to build task 'symfony:console'
```
I think found in issue 10, to use symfony:command but
```
SSHKit::Runner::ExecuteError: Exception while executing on host vagrant-front01.local: Don't know how to build task 'symfony:command'
```

my code:

```
task :before_symlink do
  on roles(:front) do |host|
    #generate browser detection cache file
    invoke 'symfony:command', 'browscap:update'

    #dump assets (if using assetic)"
    invoke 'symfony:command', 'assetic:dump'

    #set queue attributes
    invoke 'symfony:command', 'app:queue:sqs:set-attributes'

    #translations
    invoke 'symfony:command', 'app:translation:sync'
  end
end

namespace :deploy do
  before :starting, 'composer:install_executable'

  before :publishing, 'before_symlink'

  after :finishing, "deploy:cleanup"
end
```

how can I run a console command? :0

Versions:
gem list | grep capistrano
capistrano (3.2.1, 2.15.5)
capistrano-composer (0.0.4)
capistrano-file-permissions (0.1.0)
capistrano-symfony (0.3.0)

I did just find this thuo:
https://github.com/capistrano/symfony/blob/master/lib/capistrano/tasks/symfony.rake#L21

ok, i'll go back to symfony:console.

**Comment by peterjmit** [comment]
This has since been fixed 

See 
* https://github.com/capistrano/symfony/blob/f557b3ce2cb0a90d43704e73a9dbda8ea170fb0e/capistrano-symfony.gemspec#L21-L30
* https://github.com/capistrano/symfony/releases/tag/0.4.0

Sorry for any confusion!
