### ISSUE TITLE
set own environment variable for console commands

### ISSUE THREAD

**Issue by jurgenweber** [capistrano/symfony#30]
how can i do it?

I can see in debug log:

DEBUG[79c9a742] Command: cd /var/www/asdf/asdf/shared && ( SYMFONY_ENV=prod /usr/bin/env [ -e composer.phar ] )

how can i add another param to that SYMFONY_ENV?

**Comment by pborreli** [comment]
If you want to define other env variables you can use : 

```
set :default_env, {
  'DATABASE_NAME' => 'symfony',
  'DATABASE_USER' => 'user',
  'DATABASE_PASSWORD' => 'password'
}

**Comment by peterjmit** [comment]
Closing this issue, thanks for helping @pborreli :smile:
