### ISSUE TITLE
parameters.yml updates

### ISSUE THREAD

**Issue by carlcraig** [capistrano/symfony#36]
It would be nice to have a built in task to sync `parameters.yml` with the `dist` version.

I have created a couple of simple tasks which provide this functionality: https://gist.github.com/carlcraig/377ed30bfa2015ea5049

Im not sure if they are worth integrating into this module (and I wouldn't know where to start with integrating them).

Hopefully they are useful.

**Comment by peterjmit** [comment]
Hi @carlcraig,

Thanks for the suggestions, but `parameters.yml` is a file that is very much specific to the environment and often contains secrets such as database passwords and the like.

Capistrano is not really the best tool for sensitive information as its primary datasource is usually a source code repository and that kind of info should __never__ be stored in the repo. A such I would not be looking to include these changes here.

If you want to have deployment/changes to `parameters.yml` managed in an automated fashion a server configuration/orchestration tool such as chef/puppet/ansible/salt etc or some kind of service discovery _thing_ is where that should happen. 

Alternatively if the values do not change between environments (and are only added when `.dist` is updated) then they probably belong in one of your `config*.yml` files

That said if you don't use any of the above and you still find this useful then why not make it a little more generic (i.e. compatibility with any yaml file) and release a general capistrano plugin for the community. Integration with symfony is easy with `before`/`after` hooks as mentioned in your gist.

**Comment by carlcraig** [comment]
No worries.

The idea with the tasks is to prompts the user to enter the values, to *avoid* saving them in `VCS`, and ensure that the shared `parameters.yml` contains all the required parameters specified in the `dist` file similar to https://github.com/Incenteev/ParameterHandler.

That being said environment variables are probably the best solution for this, where something like chef/puppet/ansible would be a more appropriate tool.

I agree that it would most likely be better suited to handle generic `yml` files instead of just `parameters.yml` and therefore should most likely be its own capistrano plugin.

Thanks for your Feedback.
