### ISSUE TITLE
Cannot load such file -- capistrano/symfony

### ISSUE THREAD

**Issue by flo-sch** [capistrano/symfony#39]
Hey guys,

First, apologies if this problem is not related to this repository,
This is my very first time with capistrano and ruby in general.

When I try to launch any capistrano command  such as ````cap deploy:setup````, it fails with the following error:

	(Backtrace restricted to imported tasks)
	cap aborted!
	LoadError: cannot load such file -- capistrano/symfony

I am using OS X 10.10.3

````ruby -v: ruby 2.0.0p481 (2014-05-08 revision 45883) [universal.x86_64-darwin14]````
````gem -v: 2.0.14````

Here is my local configuration (root is my application project folder):

Gemfile:

	source "https://rubygems.org"

	# Capistrano/symfony
	gem 'capistrano', '~> 3.1'
	gem 'capistrano-symfony', '~> 0.1', :github => 'capistrano/symfony'

Capfile:

	require 'capistrano/symfony'

	load 'my-deploy-configuration-file.rb'

I've also run ````bundle install````.
When I run ````bundle show````, I've got the following:

	Gems included by the bundle:
	  * bundler (1.10.5)
	  * capistrano (3.4.0)
	  * capistrano-composer (0.0.6)
	  * capistrano-file-permissions (0.1.1)
	  * capistrano-symfony (0.4.0 f557b3c)
	  * colorize (0.7.7)
	  * i18n (0.7.0)
	  * net-scp (1.2.1)
	  * net-ssh (2.9.2)
	  * rake (10.4.2)
	  * sshkit (1.7.1)

I've also tried replacing ````capistrano/symfony```` by ````capistrano-symfony```` in my Capfile, but the error is the same (````Cannot load such file -- capistrano-symfony````)

Did I miss a step?

**Comment by evoactivity** [comment]
For some reason it's installing as symfony-f557b3ce2cb0 in your /Users/you/.bundler/ruby/2.0.0/gems directory, rename that to capistrano-symfony and that seems to fix it.

**Comment by salemgolemugoo** [comment]
@evoactivity it's not working for me also

**Comment by tomcyr** [comment]
```bash
gem install capistrano-symfony
```
resolved this problem
