### ISSUE TITLE
Wrong configuration param for capistrano/file-permissions

### ISSUE THREAD

**Issue by zaerl** [capistrano/symfony#40]
**capistrano/symfony** does use a variable called **webserver_user** for storing the usename used by **use_set_permissions** which is incorrect.

The [correct variable](https://github.com/capistrano/file-permissions/blob/master/lib/capistrano/tasks/file-permissions.rake#L82) read by file-permissions is: **file_permissions_users**.

**Comment by gerryvdm** [comment]
At the very least, the README.md should be updated as it is wrong in stating `set :file_permissions_users, ['www-data']` is the default value. By default no extra users are given permissions.

**Comment by peterjmit** [comment]
Fixed in #50
