### ISSUE TITLE
Exporting of SYMFONY_ENV

### ISSUE THREAD

**Issue by zaerl** [capistrano/symfony#42]
It seems that capistrano/symfony do not export the SYMFONY_ENV variable. Given this post-install-cmd scripts do not run in the chosen environment. I set this in my deploy script and now everything work well.

``` ruby
   set :default_env, {
     'SYMFONY_ENV' => 'prod'
   }
```

**Comment by webdevilopers** [comment]
Is this still an issue? Had no problems so far with the default config value:
```ruby
# Symfony environment
set :symfony_env,  "prod"
```

Can you post any post-install-cmd script that fails?

**Comment by sagikazarmark** [comment]
This is what I can see in the capistrano log:

```
  INFO [d970e0e3] Running MY_PATH/shared/composer.phar install --no-dev --prefer-dist --no-interaction --quiet --optimize-autoloader as user@host
 DEBUG [d970e0e3] Command: cd MY_PATH/releases/20160318111655 && ( export SYMFONY_ENV="prod" ; MY_PATH/shared/composer.phar install --no-dev --prefer-dist --no-interaction --quiet --optimize-autoloader )
  INFO [d970e0e3] Finished in 9.869 seconds with exit status 0 (successful).
```

This is actually done [here](https://github.com/capistrano/symfony/blob/master/lib/capistrano/tasks/set_symfony_env.rake#L3)
