### ISSUE TITLE
Error: no implicit conversion of nil into String

### ISSUE THREAD

**Issue by jgettings** [capistrano/symfony#46]
I'm having an issue using the default values for some of the available options in this plugin. If I just add "require 'capistrano/symfony'" to my deploy.rb, I get an error about symfony_cache_path being null. I played around with this locally to see if I could figure out what was happening, it seems like either defaults.rb or paths.rb isn't really running or is running in the wrong order, but I'm not familiar with ruby/capistrano enough to really know how it's supposed to happen.

Note, this is an old project that I was in the process of converting over from capifony to capistrano 3 and it is stuck on symfony 2.2.1 for now. Not sure if that would cause this issue though. 

**Workaround**
This is a totally valid workaround, so I'm not really concerned about this bug getting resolved, I just wanted to note it in case anyone else ran into this issue. 

_It works fine if you just set the cache_path in deploy.rb_. I get other errors but I didn't look into those as deeply. I really wanted to just use the defaults, but I wound up just copying the defaults from the readme and adding those to my project's deploy.rb.
> set :app_path, "app"
> set :cache_path, fetch(:app_path) + "/cache"

----
More things in case anyone wants to try to resolve this...
**Stack Trace**
```
** Invoke symfony:create_cache_dir (first_time)
** Execute symfony:create_cache_dir
DEBUG [eab82b51] Running /usr/bin/env if test ! -d /srv/oved/prps/releases/20151023124234; then echo "Directory does not exist '/srv/oved/prps/releases/20151023124234'" 1>&2; false; fi as studio@ssh.studiolabs.com
DEBUG [eab82b51] Command: if test ! -d /srv/oved/prps/releases/20151023124234; then echo "Directory does not exist '/srv/oved/prps/releases/20151023124234'" 1>&2; false; fi
DEBUG [eab82b51] Finished in 0.086 seconds with exit status 0 (successful).
cap aborted!
SSHKit::Runner::ExecuteError: Exception while executing as studio@ssh.studiolabs.com: no implicit conversion of nil into String
/usr/local/rvm/rubies/ruby-2.0.0-p643/lib/ruby/gems/2.0.0/gems/sshkit-1.7.1/lib/sshkit/runners/parallel.rb:16:in `rescue in block (2 levels) in execute'
/usr/local/rvm/rubies/ruby-2.0.0-p643/lib/ruby/gems/2.0.0/gems/sshkit-1.7.1/lib/sshkit/runners/parallel.rb:12:in `block (2 levels) in execute'
TypeError: no implicit conversion of nil into String
/usr/local/rvm/rubies/ruby-2.0.0-p643/lib/ruby/2.0.0/pathname.rb:392:in `initialize'
/usr/local/rvm/rubies/ruby-2.0.0-p643/lib/ruby/2.0.0/pathname.rb:392:in `new'
/usr/local/rvm/rubies/ruby-2.0.0-p643/lib/ruby/2.0.0/pathname.rb:392:in `join'
/usr/local/rvm/gems/ruby-2.0.0-p643/gems/capistrano-symfony-0.4.0/lib/capistrano/symfony/dsl/paths.rb:20:in `symfony_cache_path'
/usr/local/rvm/gems/ruby-2.0.0-p643/gems/capistrano-symfony-0.4.0/lib/capistrano/tasks/symfony.rake:59:in `block (4 levels) in <top (required)>'
/usr/local/rvm/rubies/ruby-2.0.0-p643/lib/ruby/gems/2.0.0/gems/sshkit-1.7.1/lib/sshkit/backends/abstract.rb:77:in `within'
/usr/local/rvm/gems/ruby-2.0.0-p643/gems/capistrano-symfony-0.4.0/lib/capistrano/tasks/symfony.rake:58:in `block (3 levels) in <top (required)>'
/usr/local/rvm/rubies/ruby-2.0.0-p643/lib/ruby/gems/2.0.0/gems/sshkit-1.7.1/lib/sshkit/backends/netssh.rb:54:in `instance_exec'
/usr/local/rvm/rubies/ruby-2.0.0-p643/lib/ruby/gems/2.0.0/gems/sshkit-1.7.1/lib/sshkit/backends/netssh.rb:54:in `run'
/usr/local/rvm/rubies/ruby-2.0.0-p643/lib/ruby/gems/2.0.0/gems/sshkit-1.7.1/lib/sshkit/runners/parallel.rb:13:in `block (2 levels) in execute'
Tasks: TOP => symfony:create_cache_dir
The deploy has failed with an error: Exception while executing as studio@ssh.studiolabs.com: no implicit conversion of nil into String
```

**Some Other Info**
I'm on a Vagrant instance running a precise32 box, here are some versions of things:

& ruby -v
ruby 2.0.0p643 (2015-02-25 revision 49749) [i686-linux]
& rvm -v
rvm 1.26.11 (latest) by Wayne E. Seguin <wayneeseguin@gmail.com>, Michal Papis <mpapis@gmail.com> [https://rvm.io/]
& gem list

*** LOCAL GEMS ***

bigdecimal (1.2.0)
bundler-unload (1.0.2)
capifony (2.8.6)
capistrano (3.4.0, 2.15.6)
capistrano-composer (0.0.6)
capistrano-file-permissions (0.1.1)
capistrano-maintenance (0.0.3)
capistrano-symfony (0.4.0)
chunky_png (1.3.4)
colored (1.2)
colorize (0.7.7)
compass (1.0.3)
compass-core (1.0.3)
compass-import-once (1.0.5)
executable-hooks (1.3.2)
ffi (1.9.10)
gem-wrappers (1.2.7)
highline (1.7.8)
hipchat (1.5.2)
httparty (0.13.7)
i18n (0.7.0)
inifile (2.0.2)
io-console (0.4.2)
json (1.8.3, 1.7.7)
mimemagic (0.3.0)
minitest (4.3.2)
multi_json (1.11.2)
multi_xml (0.5.5)
net-scp (1.2.1)
net-sftp (2.1.2)
net-ssh (3.0.1)
net-ssh-gateway (1.2.0)
psych (2.0.0)
rainbow (2.0.0)
rake (10.4.2, 0.9.6)
rb-fsevent (0.9.6)
rb-inotify (0.9.5)
rdoc (4.0.0)
ruby-progressbar (1.4.1)
rubygems-bundler (1.4.4)
rvm (1.11.3.9)
sass (3.4.19)
scss_lint (0.42.2)
scss_lint_reporter_checkstyle (0.2.0)
sshkit (1.7.1)
terminal-notifier (1.6.3)
test-unit (2.0.0.0)

**Comment by maximelebastard** [comment]
+1

**Comment by peterjmit** [comment]
@jgettings Thanks for the detailed report, if you have a chance to play around with the new release and this is still a problem can you reopen?

https://github.com/capistrano/symfony/releases/tag/1.0.0.rc1

**Comment by folliked** [comment]
i have still the problem with the 1.0.0.rc1 and rc2 ... the work around doesn't work. I have open an issue for this.

**Comment by JulienBreux** [comment]
Same problem
