### ISSUE TITLE
parameters.yml not symlinked on FreeBSD

### ISSUE THREAD

**Issue by webdevilopers** [capistrano/symfony#52]
I just updated a symfony app that used capifony with capistrano 2.

I use all the default values without adding `parameters.yml` to the `:linked_files`.

For some reason the symlink is not created. The app will deploy and use the non-shared file under `app/config/parameters.yml`.

The command is executed:
**Running /usr/bin/env [ -f /usr/local/www/apache24/noexec/foobar/shared/app/config/parameters.yml ] as foobar@example.com
DEBUG [95af9b97] Command: [ -f /usr/local/www/apache24/noexec/foobar/shared/app/config/parameters.yml ]**

The following message is used by Symfony itself, not Capistrano, I think:
**> Incenteev\ParameterHandler\ScriptHandler::buildParameters
DEBUG [a9e4aa32] 	Creating the "app/config/parameters.yml" file**

When I add `:linked_files` as mentioned in https://github.com/capistrano/symfony/issues/11#issuecomment-44615251:
```ruby
set :linked_files, [fetch(:app_path) + '/config/parameters.yml']
```
I get:
```
Incenteev\ParameterHandler\ScriptHandler::buildParameters
Script Incenteev\ParameterHandler\ScriptHandler::buildParameters handling the post-install-cmd event terminated with an exception
                                                
  file_put_contents(app/config/parameters.yml): failed to open stream: Permission denied
```

Are there any sepcial privileges to allow symlinking? Does the `:webserver_user` require `sudo`?

Never had problems with the default configuration on Debian. Maybe this is a FreeBSD issue. For instance there is no `www-data` User or group on this server. The group is `vuser`.

I've encountered many problems with Capistrano with FreeBSD. Problems with `setfacl` (https://github.com/capistrano/symfony/issues/40), default bash (https://github.com/capistrano/symfony/issues/24) and others. Maybe there is a problem with symlinks in general too:
http://www.freebsddiary.org/ln.php

**Comment by greg0ire** [comment]
Did you configure these settings accordingly : 

```
# Name used by the Web Server (i.e. www-data for Apache)
set :file_permissions_users, ['www-data']

# Name used by the Web Server (i.e. www-data for Apache)
set :webserver_user,        "www-data"
```
?

**Comment by webdevilopers** [comment]
The directory on our FreeBSD server have the `vuser` group by default, not the typical apache `www-data`. This is the config I tried:

```ruby
# Name used by the Web Server (i.e. www-data for Apache)
set :file_permissions_users, ['vuser']

# Name used by the Web Server (i.e. www-data for Apache)
set :webserver_user,        "foobar"

set :permission_method,     :acl
set :use_set_permissions,   true
```

What are the requirements for user and group to make it work? I could ask our provider about the best settings.

**Comment by greg0ire** [comment]
> set :webserver_user,        "foobar"

Why isn't it vuser ?

> What are the requirements for user and group to make it work? I could ask our provider about the best settings.

I don't know, I banged my head myself with a similar ACL issues the other day, and decided to limit the use of ACLs through capistrano to the cache directory, which is the only www-data-writable-dir that is not linked in `shared`.

**Comment by webdevilopers** [comment]
The provider suggest to use `web` instead of `www-data`:
```ruby
# Name used by the Web Server (i.e. www-data for Apache)
set :file_permissions_users, ['web']

# Name used by the Web Server (i.e. www-data for Apache)
set :webserver_user,        "web"
```

The symlinks seem to work. Unfortunately I get a permission error:
```
> Incenteev\ParameterHandler\ScriptHandler::buildParameters
Script Incenteev\ParameterHandler\ScriptHandler::buildParameters handling the post-install-cmd event terminated with an exception

                                                                                          
  [ErrorException]                                                                        
  file_put_contents(app/config/parameters.yml): failed to open stream: Permission denied 
```

What kind of permissions are need here? As I mentioned I can't run `acl` for setting permissions - siee issue https://github.com/capistrano/symfony/issues/40.

**Comment by webdevilopers** [comment]
At the bottom line I switch to `chmod` using my regular user I use for SSH auth. No need to switch to `web` then. But some other issues with permissions on the `cache` folder and `logs/prod.log`.
I recently changed them to *0777* to be able to deploy.

Acl can not be used on FreeBSD with the current command:
```
SYMFONY_ENV=prod /usr/bin/env setfacl -Rm 
```

**setfacl: illegal option -- R**

I will create a new issue on the capistrano project.
