### ISSUE TITLE
installation could not find gem

### ISSUE THREAD

**Issue by khalid-s** [capistrano/symfony#58]
Hi,

I tried the installation but it does not seem to work and there are no workarounds on the web for the problem. Here is what I did:

Added capistrano/symfony in my Gemfile
```
group :development do
  gem "capistrano", "~> 3.4"
  gem 'capistrano-symfony', '~> 1.0.0.rc1'
end
```

Launched cap install
```
$ bundle exec cap install
Could not find gem 'capistrano-symfony (~> 1.0.0.rc1)' in any of the gem sources listed in your Gemfile or available on this machine.
Run `bundle install` to install missing gems.
```
As mentionned in the error, I launched bundle install:
```
$ bundle install
Your Gemfile has no gem server sources. If you need gems that are not already on your machine, add a line like this to your Gemfile:
source 'https://rubygems.org'
Could not find gem 'capistrano-symfony (~> 1.0.0.rc1)' in any of the gem sources listed in your Gemfile or available on this machine.
```

This was done on a fresh ubuntu install. Ruby 2 was installed with rvm and ruby -v returned:
```
$ ruby -v
ruby 2.0.0p643 (2015-02-25 revision 49749) [x86_64-linux]
```

**Comment by peterjmit** [comment]
It looks like you need to update your `Gemfile` to include the following line

```ruby
source 'https://rubygems.org'

group :development do
  gem "capistrano", "~> 3.4"
  gem 'capistrano-symfony', '~> 1.0.0.rc1'
end
```


> Your Gemfile has no gem server sources. If you need gems that are not already on your machine, add a line like this to your Gemfile:
source 'https://rubygems.org'
Could not find gem 'capistrano-symfony (~> 1.0.0.rc1)' in any of the gem sources listed in your Gemfile or available on this machine.

**Comment by pedroresende** [comment]
@peterjmit shouldn't the README.md be updated to reflect these changes ?
