### ISSUE TITLE
Symfony 3

### ISSUE THREAD

**Issue by khalil1608** [capistrano/symfony#60]
Could we have the same version for Symfony 3 ?

**Comment by Prometee** [comment]
Maybe this should be close ? @will-in-wi

**Comment by will-in-wi** [comment]
Does this work on Symfony 3?

**Comment by Prometee** [comment]
The directory structure change with SF 3.4 but before this version  the directory structure was the default actual one in this project. SF 3.4 has been launch last month so this ticket should be closed
