### ISSUE TITLE
bug after 0.4.0 version undefined local variable or method `symfony_cache_path' 

### ISSUE THREAD

**Issue by folliked** [capistrano/symfony#63]
00:00 deploy:symlink:linked_dirs
      01 mkdir -p /var/www/test/myproject/releases/20160610144818/app
*\* Invoke symfony:create_cache_dir (first_time)
*\* Execute symfony:create_cache_dir
cap aborted!
NameError: undefined local variable or method `symfony_cache_path' for #<SSHKit::Backend::Printer:0x007fb6b29277a8>
/Library/Ruby/Gems/2.0.0/gems/capistrano-symfony-1.0.0.rc2/lib/capistrano/tasks/symfony.rake:52:in`block (4 levels) in <top (required)>'
/Library/Ruby/Gems/2.0.0/gems/sshkit-1.10.0/lib/sshkit/backends/abstract.rb:80:in `within'
/Library/Ruby/Gems/2.0.0/gems/capistrano-symfony-1.0.0.rc2/lib/capistrano/tasks/symfony.rake:51:in`block (3 levels) in <top (required)>'
/Library/Ruby/Gems/2.0.0/gems/sshkit-1.10.0/lib/sshkit/backends/abstract.rb:29:in `instance_exec'
/Library/Ruby/Gems/2.0.0/gems/sshkit-1.10.0/lib/sshkit/backends/abstract.rb:29:in`run'
/Library/Ruby/Gems/2.0.0/gems/sshkit-1.10.0/lib/sshkit/runners/parallel.rb:12:in `block (2 levels) in execute'
Tasks: TOP => symfony:create_cache_dir
The deploy has failed with an error: undefined local variable or method`symfony_cache_path' for #SSHKit::Backend::Printer:0x007fb6b29277a8
*\* Invoke deploy:failed (first_time)
*\* Execute deploy:failed

I don't know what is missing ... i use capistrano 3.5

**Comment by quentinsikana** [comment]
I have exactly the same problem here.

@folliked have you found how to fix this?

**Comment by quentinsikana** [comment]
In the file `lib/capistrano/tasks/symfony.rake` line 53

Shouldn't we replace this
```
if test "[ -d #{symfony_cache_path} ]"
          execute :rm, "-rf", symfony_cache_path
```
with this 
```
if test "[ -d #{symfony_cache_path} ]"
          execute :rm, "-rf", fetch(:symfony_cache_path)
```
?

**Comment by folliked** [comment]
i think, it doesn't load DSL libs of capistrano/symfony

**Comment by nescim** [comment]
Did anybody find a workaround? @folliked seems to be right since the offending variable is defined in the DSL folder but I don't have enough experience with Capistrano to figure out how to include it manually and even google does not yield anythiong useful.

**Comment by MJBGO** [comment]
Same problem for me and "symfony_console" is not defined too ...

Ruby 2.3.3, Capistrano 3.7.1 and capistrano/symfony 1.0.0-rc2

Could you look @peterjmit ? I don't have enough experience with Ruby and Capistrano ...

**Comment by pbowyer** [comment]
Having recreated my Vagrant box after running for a year, I now have this error too.

```
(Backtrace restricted to imported tasks)
cap aborted!
NameError: undefined local variable or method `symfony_cache_path' for #<SSHKit::Backend::Printer:0x000000015ad308>

Tasks: TOP => symfony:create_cache_dir
(See full trace by running task with --trace)
The deploy has failed with an error: undefined local variable or method `symfony_cache_path' for #<SSHKit::Backend::Printer:0x000000015ad308>
```

**Comment by PillowPillow** [comment]
Same probleme here, did anybody find a workaround?

**Comment by arjanvdbos** [comment]
Same issue here, both undefined local variable or method `symfony_cache_path' and 'symfony_console'. It seems that the DSL file is parsed (putting gibberish in it results in an parse error), but not actually used/available.

- Ruby 2.5.1
- Capistrano 3.10.2
- capistrano/symfony 1.0.0-rc3

Nobody found a workaround yet? I don't have a lot of experience with Ruby in order to do proper debugging.

**Comment by Nyholm** [comment]
Closing this due inactivity. Feel free to ping me if this is still an issue.

**Comment by HeahDude** [comment]
I ran into this issue today. Trying to use `--dry-run` seems broken, which is sad as it prevents proper debugging.

**Comment by Prometee** [comment]
@Nyholm it's still happening using latest gem package versions.

I run `cap prod deploy --dry-run` and here the error stack trace:

```
** Invoke symfony:create_cache_dir (first_time)
** Execute symfony:create_cache_dir
#<Thread:0x000000015a8c3c40@<redacted>/ruby/2.6.0/gems/sshkit-1.23.2/lib/sshkit/runners/parallel.rb:10 run> terminated with exception (report_on_exception is true):
<redacted>/ruby/2.6.0/gems/sshkit-1.23.2/lib/sshkit/runners/parallel.rb:15:in `rescue in block (2 levels) in execute': Exception while executing as www-data@shop.flux.audio: undefined local variable or method `symfony_cache_path' for #<SSHKit::Backend::Printer:0x000000015a8c3ad8> (SSHKit::Runner::ExecuteError)
        from <redacted>/ruby/2.6.0/gems/sshkit-1.23.2/lib/sshkit/runners/parallel.rb:11:in `block (2 levels) in execute'
<redacted>/ruby/2.6.0/gems/capistrano-symfony-2.0.0/lib/capistrano/tasks/symfony.rake:52:in `block (4 levels) in <top (required)>': undefined local variable or method `symfony_cache_path' for #<SSHKit::Backend::Printer:0x000000015a8c3ad8> (NameError)
        from <redacted>/ruby/2.6.0/gems/sshkit-1.23.2/lib/sshkit/backends/abstract.rb:92:in `within'
        from <redacted>/ruby/2.6.0/gems/capistrano-symfony-2.0.0/lib/capistrano/tasks/symfony.rake:51:in `block (3 levels) in <top (required)>'
        from <redacted>/ruby/2.6.0/gems/sshkit-1.23.2/lib/sshkit/backends/abstract.rb:31:in `instance_exec'
        from <redacted>/ruby/2.6.0/gems/sshkit-1.23.2/lib/sshkit/backends/abstract.rb:31:in `run'
        from <redacted>/ruby/2.6.0/gems/sshkit-1.23.2/lib/sshkit/runners/parallel.rb:12:in `block (2 levels) in execute'
cap aborted!
```

Reading the code I think the library is wanting to create the cache directory but because `dry-run` is used the parent directory is not even existing.
I don't know if Capistrano or ruby provide a way to virtually create/check/mv/rm directories or files while using `dry-run`.
