### ISSUE TITLE
My parameters.yml file gets overriden

### ISSUE THREAD

**Issue by migmolrod** [capistrano/symfony#71]
I upload a "production" app/config/parameters.yml, but then "composer install" is invoked so it overrides that custom parameters.yml and post-install scripts from Symfony's composer fail since it can't connect to database.

How can I handle this?

**Comment by jmily** [comment]
@migmolrod , I followed the example [Symfony3 Capistrano Example](https://codestory.me/symfony3-deployment-capistrano-example/) and it's working for me. Basically, uploading your parameters.yml file to the shared folder of your production server and set the linked files.
