### ISSUE TITLE
'execute' should be wrapped in an 'on' scope

### ISSUE THREAD

**Issue by NicolasNSSM** [capistrano/symfony#73]
I'm trying to deploy a SF3 app with  
- capistrano-3.6.1
- capistrano-symfony-1.0.0.rc2

I got an error : 

```
** Invoke symfony:schema_update (first_time)
** Execute symfony:schema_update
Warning: 'execute' should be wrapped in an 'on' scope in /usr/local/bundle/gems/capistrano-symfony-1.0.0.rc2/lib/capistrano/dsl/symfony.rb:52.

  task :example do
    on roles(:app) do
      execute 'whoami'
    end
  end

cap aborted!
```

I think someone just has to add a "on roles" there, but as i'm using it on a gitlab docker runner, i can't easily edit the file and test it...

**Comment by Nyholm** [comment]
This is fixed in master
