### ISSUE TITLE
Release a stable release?

### ISSUE THREAD

**Issue by Nyholm** [capistrano/symfony#80]
Rc2 is over a year old now. What are we missing before we can do a stable release?

**Comment by skonsoft** [comment]
Any news ?

thanks

**Comment by scuben** [comment]
bump?

**Comment by will-in-wi** [comment]
This comment contains some of the difficulties: https://github.com/capistrano/symfony/issues/83#issuecomment-352929169

**Comment by adfinlay** [comment]
Would it be possible to get RC3 added to rubygems please?

**Comment by Nyholm** [comment]
Yes, I have pinged Peter about giving me permission on rubygems.org

**Comment by Nyholm** [comment]
Done, It up now https://rubygems.org/gems/capistrano-symfony
